In [2]:
import gymnasium as gym
import cv2
import numpy as np


In [3]:
# ====================================================
# Q es la tabla con los Q-valores. PI es la politica
# Durante el entrenamiento la politica elige al azar
# 40% de las veces, mientras que elige la mejor
# decision el 60%
# ====================================================

Q = np.zeros((16,4),dtype=np.float32)

def pi(s,test=False):
    if np.random.random()<0.4 and not test:
        return np.random.randint(0,4)
    else:
        return np.random.choice(np.flatnonzero(Q[s] == Q[s].max()))
    


In [17]:
# ==============================================================================
# env es el environtmient. Gym pertence a OpenAI y es una especie de estandar
# ==============================================================================
env = gym.make('FrozenLake-v1', desc=None, map_name="4x4", is_slippery=False,render_mode='rgb_array')

alpha = 0.3
gamma = 0.99


for i in range(100):
    state,_ = env.reset()
    end,trunc = False,False
    while not (end or trunc):
        action = pi(state)																# DADO EL ESTADO ACTUAL ELIGO UNA ACCION
        next_state, reward, end, trunc, info = env.step(action)							# SI REALIZO LA ACCION EL ENVIRONMENT ME ENTREGA EL NUEVO ESTADO + LA RECOMPENZA
        Q[state,action] += alpha*(reward+gamma*Q[next_state].max()-Q[state,action])		# ECUACION DE BELLMAN. EL Q-VALOR SE ACTUALIZA EN BASE A LA RECOMPENZA Y AL MEJOR Q-VALOR
        state = next_state																# DEL SIGUIENTE ESTADO
print(Q)

[[0.9414797  0.95098966 0.93206483 0.9414797 ]
 [0.9414797  0.         0.9165489  0.93084145]
 [0.93154424 0.14802316 0.         0.        ]
 [0.2759033  0.         0.         0.        ]
 [0.95098966 0.96059567 0.         0.9414797 ]
 [0.         0.         0.         0.        ]
 [0.         0.9800986  0.         0.30212358]
 [0.         0.         0.         0.        ]
 [0.96059567 0.         0.9702987  0.95098966]
 [0.96059567 0.9800998  0.9800998  0.        ]
 [0.9702987  0.9899999  0.         0.97028995]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9800998  0.9899999  0.9702987 ]
 [0.9800998  0.9899999  0.99999994 0.9800998 ]
 [0.         0.         0.         0.        ]]


In [19]:
# ==========================================================
#          DIBUJITO
# PARA CERRARLO APRETAR LA TECLA Q CON LA VENTANA DEL
# DIBJUITO ACTIVA ( O SINO SE PEGA )
# ==========================================================
state,_ = env.reset()

end,trunc = 0,0
while 1:
    frame = cv2.cvtColor(env.render(),cv2.COLOR_BGR2RGB)
    cv2.imshow('bla',frame)

    if end or trunc:
        break
    if cv2.waitKey(200) == ord('q'):
        break

    action = pi(state,test=True)
    state, reward, end, trunc, info = env.step(action)


print('oko')
cv2.waitKey(0)
cv2.destroyAllWindows()



oko
